dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation("org.springframework.boot:spring-boot-starter-websocket:3.5.7")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")

    runtimeOnly 'org.postgresql:postgresql'

}

tasks.named('bootJar') {
    enabled = true
}

tasks.named('jar') {
    enabled = false
}