dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation("org.springframework.boot:spring-boot-starter-websocket:3.5.7")

    runtimeOnly 'org.postgresql:postgresql'

//    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('bootJar') {
    enabled = true
}

tasks.named('jar') {
    enabled = false
}